day16/urls.py
from django.urls import re_path, path
from django.views.static import serve
from django.conf import settings
from app01.views import depart, user, pretty, admin, account, task, order, chart, upload, city

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}, name="media"),

    # Department
    path("depart/list/", depart.depart_list),
    path("depart/add/", depart.depart_add),
    path("depart/delete/", depart.depart_delete),
    path("depart/<int:nid>/edit/", depart.depart_edit),
    path("depart/multi/", depart.depart_multi),

    # User
    path("user/list/", user.user_list),
    path("user/add/", user.user_add),
    path("user/model/form/add/", user.user_model_form_add),
    path("user/<int:nid>/edit", user.user_edit),
    path("user/<int:nid>/delete", user.user_delete),

    # Mobile
    path("pretty/list/", pretty.pretty_list),
    path("pretty/add/", pretty.pretty_add),
    path("pretty/<int:nid>/edit", pretty.pretty_edit),
    path("pretty/<int:nid>/delete", pretty.pretty_delete),

    # Admin
    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
    path("admin/<int:nid>/edit", admin.admin_edit),
    path("admin/<int:nid>/delete", admin.admin_delete),
    path("admin/<int:nid>/reset", admin.admin_reset),

    # Login
    path("login/", account.login),
    path("image/code/", account.image_code),
    path("logout/", account.logout),

    # Task
    path("task/list", task.task_list),
    path("task/add", task.task_add),

    # Order
    path("order/list/", order.order_list),
    path("order/add/", order.order_add),
    path("order/delete/", order.order_delete),
    path("order/edit/", order.order_edit),
    path("order/editPage/", order.order_editPage),

    # Chart
    path("chart/list/", chart.chart_list),
    path("chart/bar/", chart.chart_bar),
    path("chart/pie/", chart.chart_pie),
    path("chart/line/", chart.chart_line),

    # form
    path("upload/form/", upload.upload_form),
    path("upload/modal/form", upload.upload_modal_form),

    # City
    path("city/list/", city.city_list),
    path("city/add/", city.city_add),
]

app01/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    """ Admin """
    username = models.CharField(verbose_name="username", max_length=32)
    password = models.CharField(verbose_name="password", max_length=64)

    def __str__(self):
        return self.username

class Department(models.Model):
    """ department table """
    title = models.CharField(verbose_name="Department Title", max_length=32)

    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """ Employee Table """
    name = models.CharField(verbose_name="Employee Name", max_length=32)
    password = models.CharField(verbose_name="password", max_length=64)
    age = models.IntegerField(verbose_name="age")
    savings = models.DecimalField(verbose_name="savings", max_digits=10, decimal_places=2, default=0)

    create_time = models.DateField(verbose_name="create date")

    # depart_id = models.BigIntegerField(verbose_name="department ID")
    # depart = models.ForeignKey(to="Department", to_fields="id", on_delete=models.CASCADE)
    depart = models.ForeignKey(verbose_name="Department", to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

    gender_choices = (
        (1, "male"),
        (2, "female"),
    )
    gender = models.SmallIntegerField(verbose_name="gender", choices=gender_choices)

class PrettyNum(models.Model):
    """ Phone Number """
    mobile = models.CharField(verbose_name="phone", max_length=11)
    price = models.IntegerField(verbose_name="price", default=0)

    level_choices = (
        (1, "1 level"),
        (2, "2 level"),
        (3, "3 level"),
        (4, "4 level")
    )
    level = models.SmallIntegerField(verbose_name="level", choices=level_choices, default=1)

    status_choice = (
        (1, "use"),
        (2, "unused")
    )
    status = models.SmallIntegerField(verbose_name="status", choices=status_choice, default=2)

class Task(models.Model):
    """ Task """
    level_choice = (
        (1, "urgent"),
        (2, "normal"),
        (3, "temporary")
    )

    level = models.SmallIntegerField(verbose_name="level", choices=level_choice, default=1)
    title = models.CharField(verbose_name="title", max_length=32)
    details = models.TextField(verbose_name="details", max_length=64)
    assignee = models.ForeignKey(verbose_name="assignee", to="Admin", on_delete=models.CASCADE)

class Order(models.Model):
    """ Order """
    oid = models.CharField(verbose_name="oid", max_length=64)
    title = models.CharField(verbose_name="title", max_length=32)
    price = models.IntegerField(verbose_name="price")

    status_choice = (
        (1, "paid"),
        (2, "unpaid")
    )

    status = models.SmallIntegerField(verbose_name="status", choices=status_choice, default=1)
    admin = models.ForeignKey(verbose_name="admin", to="Admin", on_delete=models.CASCADE)

class Boss(models.Model):
    name = models.CharField(verbose_name="Employee Name", max_length=32)
    age = models.IntegerField(verbose_name="age")
    img = models.CharField(verbose_name="img", max_length=128)

class City(models.Model):
    name = models.CharField(verbose_name="name", max_length=32)
    population = models.IntegerField(verbose_name="population")
    # 本质也是charfield,django内部自动帮助保存数据
    logo = models.FileField(verbose_name="logo", max_length=128, upload_to='city/')

app01/views/account.py
from django.shortcuts import render,redirect,HttpResponse
from django import forms

from io import BytesIO

from app01.utils.bootstrap import BootStrapForm
from app01.utils.encrypt import md5
from app01.utils.picture import generate_captcha
from app01 import models


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="username",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="password",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="code",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)



def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {"form": form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        # admin_obj = models.Admin.objects().filter(username="",password="").first()

        # 验证码校验
        user_input_code = form.cleaned_data.pop("code") #获取的是用户输入的验证码
        random_code = request.session.get("image_code", "") #获取的是随机生成的验证码

        if random_code.upper() != user_input_code.upper():
            form.add_error("code", "Code is incorrect")
            return render(request, "login.html", {"form": form})

        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            form.add_error("password", "Username or password is incorrect")
            return render(request, "login.html", {"form": form})

        # 验证成功
        # 网站生成随机字符串；写到用户浏览器的cookie中；再写入到服务器(Django默认mysql)的session中
        request.session["info"] = {"id":admin_obj.id, "name":admin_obj.username}
        request.session.set_expiry(60 * 60 * 24 * 7) # 七天免登陆
        return redirect("/admin/list/")

    return render(request, "login.html", {"form": form})

def image_code(request):
    img, code_string = generate_captcha()
    print(f"验证码文本: {code_string}")

    # 写入用户的session以便校验
    request.session["image_code"] = code_string
    # 设定六十秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    request.session.clear()
    return redirect("/login/")

app01/views/admin.py
from django.shortcuts import render,redirect
from django.core.exceptions import ValidationError

from app01 import models
from app01.utils.pagination import Pagination


def admin_list(request):
    """ Admin List """
    # info_dict = request.session["info"]
    # print(info_dict)


    data_dict = {}
    search_data = request.GET.get('q', "")   # 你输入的想要查找的数据，比如这里输入框里填写的"136"..获取到"136"
    if search_data:
        data_dict["username__contains"] = search_data  # 电话号码里包含136

    queryset = models.Admin.objects.filter(**data_dict)
    page_obj = Pagination(request, queryset, page_size=2)

    context = {
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html,
        "search_data": search_data
    }
    return render(request, "admin_list.html", context)




from django import forms
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.encrypt import md5

class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        # print(self.cleaned_data)
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))

        if confirm != pwd:
            raise ValidationError("Password not the same!")
        # 返回什么，此字段以后保存在数据库就是什么（会覆盖用户输入的值）
        return confirm


def admin_add(request):
    """ add admin """
    title = "Create Admin"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, "change.html", {"form": form, "title": title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # 因为Django会在form.is_valid()的执行过程中自动发现并调用所有以clean_<fieldname>命名的方法。
        # Django执行is_valid步：
        # 1. 先进行基本的字段验证（是否为空，长度等）
        # 2. 然后将验证好的数据放进cleaned data中，
        # 3. 然后再自动调用自定义的钩子函数进行再验证
        form.save()
        return redirect("/admin/list")
    else:
        return render(request, "change.html", {"form": form, "title": title})


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ["username"]

def admin_edit(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    msg = "data not exists"
    if not row_object:
        # return render(request, "error.html", {"msg": msg})
        return redirect("/admin/list")

    title = "Edit Admin"
    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)
        return render(request, "change.html", {"form": form, "title": title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {"form": form, "title": title})


def admin_delete(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    msg = "data not exists"
    if not row_object:
        # return render(request, "error.html", {"msg": msg})
        return redirect("/admin/list")

    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list")



class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ["password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        md5_pwd = md5(pwd)

        # 去数据库校验当前密码和新输入的密码是否一致
        exists = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exists:
            raise ValidationError("Passwaord cannot be the same as before!")

        return md5_pwd

    def clean_confirm_password(self):
        # print(self.cleaned_data)
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))

        if confirm != pwd:
            raise ValidationError("Password not the same!")
        # 返回什么，此字段以后保存在数据库就是什么（会覆盖用户输入的值）
        return confirm

def admin_reset(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    msg = "data not exists"
    if not row_object:
        # return render(request, "error.html", {"msg": msg})
        return redirect("/admin/list")

    title = "reset password - {}".format(row_object.username)
    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, "change.html", {"title": title, "form": form})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {"title": title, "form": form})

app01/views/chart.py
import json
import random

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django import forms
from datetime import datetime

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

def chart_list(request):
    return render(request, "chart_list.html")

def chart_bar(request):
    legend = ["Kris", "William"]
    series_list = [
        {
            "name": 'Kris',
            "type": 'bar',
            "data": [5, 20, 36, 10, 10, 20]
        },
        {
            "name": 'William',
            "type": 'bar',
            "data": [15, 10, 18, 5, 10, 30]
        }
    ]
    x_axis = ['Jan.', 'Feb.', 'March', 'April', 'May', 'June']
    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }

    return JsonResponse(result)

def chart_pie(request):
    db_data_list = [
        {"value": 1140, "name": 'IT Department'},
        {"value": 735, "name": 'Sales Department'},
        {"value": 580, "name": 'Production Department'},
    ]
    result = {
        "status": True,
        "data": db_data_list
    }
    return JsonResponse(result)

def chart_line(request):
    legend = ["Shanghai", "Sichuan"]
    series_list = [
        {
            "name": 'Shanghai',
            "type": 'line',
            "data": [5, 20, 36, 10, 10, 20]
        },
        {
            "name": 'Sichuan',
            "type": 'line',
            "data": [15, 10, 18, 5, 10, 30]
        }
    ]
    x_axis = ['Jan.', 'Feb.', 'March', 'April', 'May', 'June']

    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }
    return JsonResponse(result)

app01/views/city.py
import json
import os
import random

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django import forms
from django.conf import settings
from datetime import datetime



from app01 import models
from app01.utils.bootstrap import BootStrapForm, BootStrapModelForm
from app01.utils.pagination import Pagination

def city_list(request):
    if request.method == "GET":
        queryset = models.City.objects.all()
        return  render(request, "city_list.html", {"queryset": queryset})

class UpModelForm(BootStrapModelForm):
    class Meta:
        model = models.City
        fields = "__all__"

def city_add(request):
    title = "Create City"
    if request.method == "GET":
        form = UpModelForm()
        return render(request, "upload_form.html", {"form": form, "title": title})

    form = UpModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect("/city/list")
    return render(request, "upload_form.html", {"form": form, "title": title})

app01/views/task.py
import json

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django import forms

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

class TaskModelForm(BootStrapModelForm):
    class Meta:
        model = models.Task
        fields = "__all__"
        widgets = {
            "details": forms.TextInput
        }

def task_list(request):
    queryset = models.Task.objects.all().order_by("-id")
    page_obj = Pagination(request, queryset)
    form = TaskModelForm()
    context = {
        "form": form,
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html()
    }

    return render(request, "task_list.html", context)

@csrf_exempt
def task_add(request):
    # 1.用户数据校验
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {"status": True}
        return JsonResponse(data_dict)

    data_dict = {"status": False, "error": form.errors}
    return JsonResponse(data_dict, json_dumps_params={"ensure_ascii": False})

app01/templates/error.html
{% extends "layout.html" %}

{% block content%}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/order_list.html
{% extends "layout.html" %}

{% block content%}
<div>
    <div class="container">
        <div style="margin-bottom:10px;">
            <input type="button" id="btnAdd" value="Create New Order" class="btn btn-primary">
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Order List
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Order ID</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th>Admin</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                <tr uid="{{ obj.id }}">
                    <th>{{ obj.id }}</th>
                    <td>{{ obj.oid }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.admin.username }}</td>

                    <td>
                        <input uid="{{ obj.id }}" class="btn btn-primary btn-xs btn-edit" type="button" value="Edit">
                        <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="Delete">
                    </td>
                </tr>
                {% endfor%}


                </tbody>
            </table>
        </div>


        <ul class="pagination">
            {{ page_string }}
        </ul>
        <!-- Create Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"></h4>
                    </div>
                    <div class="modal-body">
                        <form id="formAdd">
                            <div class="clearfix">
                                {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative; margin-bottom: 20px">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red; position: absolute;"></span>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="btnSave">Save</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
            <div class="modal-dialog" role="document">
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                    <h4>Are you ensure to delete?</h4>
                    <p style="margin:10px 0;">All data will be clear after deleting!</p>
                    <p style="text-align: right">
                        <button id="btnConfirmDelete" type="button" class="btn btn-danger">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Back</button>
                    </p>
                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    var DELETE_ID;
    var EDIT_ID;

    $(function() {
        bindBtnAddEvent();
        bindBtnSaveEvent();
        bindBtnDeleteEvent();
        bindBtnConfirmDeleteEvent();
        binBtnEditEvent();
    })

    function bindBtnAddEvent(){
        $("#btnAdd").click(function(){
            EDIT_ID = undefined;
            $("#formAdd")[0].reset();
            $("#myModalLabel").text("Create");
            $('#myModal').modal("show");
        });
    }

    function bindBtnSaveEvent(){
        $("#btnSave").click(function(){

            $(".error-msg").empty();
            if(EDIT_ID){
                doEdit();
            }else{
                doAdd();
            }
        });
    }

    function doAdd(){
        $.ajax({
            url: "/order/add/",
            type: "POST",
            data: $("#formAdd").serialize(),
            dataType: "JSON",
            success:function(res){
                if (res.status){
                    $("#formAdd")[0].reset();
                    $('#myModal').modal("hide");
                    location.reload()
                } else {
                    $.each(res.error, function(name, data){
                        $("#id_" + name).next().text(data[0])
                    })
                }
            }
        })
    }

    function doEdit(){
        $.ajax({
            url: "/order/editPage/" + "?uid=" + EDIT_ID,
            type: "POST",
            data: $("#formAdd").serialize(),
            dataType: "JSON",
            success:function(res){
                if (res.status){
                    $("#formAdd")[0].reset();
                    $('#myModal').modal("hide");
                    location.reload()
                } else {
                    if(res.tips){
                        alert(res.tips);
                    }else{
                        $.each(res.error, function(name, data){
                            $("#id_" + name).next().text(data[0])
                        })
                    }
                }
            }
        })
    }



    function bindBtnDeleteEvent(){
        $(".btn-delete").click(function(){
            // alert("click delete");
            $('#deleteModal').modal("show");

            var uid = $(this).attr("uid"); // button整了个uid类型，点击后能够在此获得当前的uid
            DELETE_ID = uid; // 将uid赋值城全局变量
        });
    }

    function bindBtnConfirmDeleteEvent(){
        $("#btnConfirmDelete").click(function(){
            $.ajax({
                url: "/order/delete/",
                type: "GET",
                data: {
                    uid: DELETE_ID
                },
                dataType: "JSON",
                success:function(res){
                    if(res.status){
                        // alert("delete successfully");
                        $('#deleteModal').modal("hide");

                        $("tr[uid='" + DELETE_ID + "']").remove();
                        DELETE_ID = 0;
                        // location.reload();



                    }else{
                        alert(res.error);
                    }
                }
            });
        });
    }

    function binBtnEditEvent(){
        $(".btn-edit").click(function(){
            $("#formAdd")[0].reset();
            var uid = $(this).attr("uid");
            EDIT_ID = uid;

            $.ajax({
                url: "/order/edit/",
                type: "GET",
                data:{
                    uid: uid
                },
                dataType: "JSON",
                success: function(res){
                    if(res.status){
                        console.log(res.data)
                        $.each(res.data, function(name, data){
                            $("#id_" + name).val(data);
                        })

                        $("#myModalLabel").text("Edit");
                        $('#myModal').modal("show");
                    }else{
                        alert(res.error);
                    }
                }

            })
        });
    }













</script>

{% endblock%}

app01/templates/task_list.html
{% extends "layout.html" %}

{% block content%}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Task List</div>
        <div class="panel-body">
            <form id="formAdd">
                <div class="clearfix">
                    {% for field in form %}
                    <div class="col-xs-6">
                        <div class="form-group" style="position: relative; margin-bottom: 20px">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span class="error-msg" style="color: red; position: absolute;"></span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-xs-12">
                    <button id="btnAdd" type="button" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            Task List
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Level</th>
                <th>Assignee</th>
                <th>Operations</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <th>{{ obj.id }}</th>
                <td>{{ obj.title }}</td>
                <td>{{ obj.get_level_display }}</td>
                <td>{{ obj.assignee.username }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="#">edit</a>
                    <a class="btn btn-danger btn-xs" href="#">delete</a>
                </td>
            </tr>
            {% endfor%}


            </tbody>
        </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function(){
        bindBtnAddEvent();
    })

    function bindBtnAddEvent(){
        $("#btnAdd").click(function(){

            $(".error-msg").empty();

            $.ajax({
                url: "/task/add",
                type: "POST",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function(res){
                    console.log(res);
                    if (res.status){
                        alert("add successfully")
                        // 用JS实现页面刷新
                        location.reload();
                    } else {
                        console.log(res.error)
                        $.each(res.error, function(name, data){
                            console.log(name, data);
                            $("#id_" + name).next().text(data[0])

                        })
                    }
                }

            })
        })
    }

</script>
{% endblock %}

app01/templates/user_list.html
{% extends "layout.html" %}

{% block content%}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Create User
            </a>
            <a class="btn btn-success" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Create User (Model Form)
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                User List
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User Name</th>
                    <th>Password</th>
                    <th>Age</th>
                    <th>Savings</th>
                    <th>Create Time</th>
                    <th>Gender</th>
                    <th>Department</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                <tr>
                    <th>{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.savings }}</td>
                    <td>{{ obj.create_time|date:"Y-m-d"}}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit">edit</a>
                        <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete">delete</a>
                    </td>
                </tr>
                {% endfor%}


                </tbody>
            </table>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
</div>
{% endblock %}